services:
  codrawing-versus:
    image: botpaint:latest
    platform: linux/amd64
    build:
      context: .
      target: game
  codrawing-versus-player:
    image: botpaint-player:latest
    platform: linux/amd64
    build:
      context: .
      target: player
