services:
  codrawing-versus:
    image: coplace-versus:latest
    platform: linux/amd64
    build:
      context: .
      target: game
  codrawing-versus-player:
    image: coplace-versus-player:latest
    platform: linux/amd64
    build:
      context: .
      target: player
